"""
Code generated by Claude Sonnet 4.6 on Apr 18 2026.

Scrape food shelf names and addresses from hungersolutions.org
Uses the FacetWP AJAX endpoint to get all results in bulk.

Requirements:
    requests 
    beautifulsoup4
"""

import csv
import json
import time
import requests
from bs4 import BeautifulSoup

BASE_URL = "https://www.hungersolutions.org/find-help/"
HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; data-research/1.0)",
    "Content-Type": "application/x-www-form-urlencoded",
}


def fetch_page(page_number, per_page=50):
    """Fetch one page of results via FacetWP's AJAX endpoint."""
    payload = {
        "action": "facetwp_refresh",
        "data[facets][categories][]": "food-shelves",
        "data[pager][page]": page_number,
        "data[pager][per_page]": per_page,
    }
    resp = requests.post(BASE_URL, headers=HEADERS, data=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()


def parse_listing(html_fragment):
    """Parse name and address out of a single listing card's HTML."""
    soup = BeautifulSoup(html_fragment, "html.parser")
    results = []
    for item in soup.select(".fwp-result, .result-item, article, .location-item, li"):
        # Try common patterns for name + address
        name_el = item.select_one("h2, h3, .location-name, .entry-title, strong")
        addr_el = item.select_one(".address, .location-address, address, p")
        name = name_el.get_text(strip=True) if name_el else ""
        addr = addr_el.get_text(strip=True) if addr_el else ""
        if name:
            results.append({"name": name, "address": addr})
    return results


def main():
    all_records = []
    page = 1
    per_page = 50

    print("Fetching page 1 to determine total count...")
    try:
        data = fetch_page(page, per_page)
    except Exception as e:
        print(f"ERROR on page 1: {e}")
        print("\nFallback: Trying direct GET with large per_page...")
        # Some FacetWP setups respond to GET with a per_page override
        resp = requests.get(
            BASE_URL,
            params={"fwp_categories": "food-shelves", "fwp_per_page": 600},
            headers=HEADERS,
            timeout=30,
        )
        soup = BeautifulSoup(resp.text, "html.parser")
        for item in soup.select("article, .result-item, .location"):
            name_el = item.select_one("h2, h3, .entry-title, strong")
            addr_el = item.select_one(".address, address, p")
            name = name_el.get_text(strip=True) if name_el else ""
            addr = addr_el.get_text(strip=True) if addr_el else ""
            if name:
                all_records.append({"name": name, "address": addr})
        write_csv(all_records)
        return

    # FacetWP returns {"template": "<html>...", "pager": {"total_rows": N, ...}}
    total = data.get("pager", {}).get("total_rows", 0)
    print(f"  Total records reported: {total}")

    html = data.get("template", "")
    records = parse_listing(html)
    all_records.extend(records)
    print(f"  Page 1: found {len(records)} records")

    total_pages = -(-total // per_page)  # ceiling division
    for pg in range(2, total_pages + 1):
        print(f"Fetching page {pg}/{total_pages}...")
        try:
            data = fetch_page(pg, per_page)
            html = data.get("template", "")
            records = parse_listing(html)
            all_records.extend(records)
            print(f"  Page {pg}: found {len(records)} records")
        except Exception as e:
            print(f"  ERROR on page {pg}: {e}")
        time.sleep(0.5)  # be polite

    print(f"\nTotal records scraped: {len(all_records)}")
    write_csv(all_records)


def write_csv(records):
    outfile = "data/mn_food_shelf_list.csv"
    with open(outfile, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["name", "address"])
        writer.writeheader()
        writer.writerows(records)
    print(f"Saved to {outfile}")


if __name__ == "__main__":
    main()
